---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# SpGPCW: Spatially Varying Gaussian Process Model for Critical Window Estimation

## Statistical Model
$$Y_{ij}|\boldsymbol{\beta}, \boldsymbol{\theta}_i \stackrel{\text{ind}}{\sim} \text{Binomial}\left\{c_{ij}, p_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)\right\},\ i=1,...,s;\ j=1,...,n_i;$$

$$\log\left\{\frac{p_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)}{1 - p_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)}\right\} = \textbf{x}_{ij}^{\text{T}} \boldsymbol{\beta} + \sum_{k=1}^{m_{ij}} \text{z}_{ijk} \theta_i\left(k\right);$$

$$\boldsymbol{\theta}= \left(\boldsymbol{\theta}_1^{\text{T}}, ..., \boldsymbol{\theta}_s^{\text{T}}\right)^{\text{T}};\ \boldsymbol{\theta}_i=\left\{\theta_i\left(1\right), ..., \theta_i\left(m\right)\right\}^{\text{T}};$$

$$\boldsymbol{\theta}_i|\boldsymbol{\theta}_{-i}, \rho, \phi, \sigma^2_{\theta}, \boldsymbol{\eta}, \stackrel{\text{ind}}{\sim}\text{MVN}\left\{\frac{\rho \sum_{j=1}^s w_{ij}\boldsymbol{\theta}_j + \left(1 - \rho\right)\boldsymbol{\eta}}{\rho \sum_{j=1}^s w_{ij} + \left(1-\rho\right)}, \frac{\sigma^2_{\theta}\Sigma\left(\phi\right)}{\rho \sum_{j=1}^s w_{ij} + \left(1 - \rho\right)}\right\},\ i=1,...,s;$$

$$\boldsymbol{\eta}=\left\{\eta\left(1\right), ..., \eta\left(m\right)\right\}^{\text{T}}| \sigma^2_{\eta}, \phi \sim \text{MVN}\left\{\boldsymbol{0}_m, \sigma^2_{\eta}\Sigma\left(\phi\right)\right\};$$

$$\Sigma\left(\phi\right)_{ij} = \exp\left\{-\phi |i-j|\right\},\ \phi > 0;$$

* $m = \max\left\{m_{ij}: i=1,...,s;\ j=1,...,n_i\right\};$

* $s$: Number of unique spatial locations;

* $n_i$:  Number of observations with spatial location $i$;

* $\boldsymbol{0}_m$: Length $m$ vector with each entry equal to zero.

## Prior Information
$\beta_j \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\beta}\right),\ j=1,...,p;$

* $p$: Length of $\textbf{x}_{ij}$ vector (same for all $i$, $j$);

* Default setting: $\sigma^2_{\beta} = 10,000.$

$\sigma^2_{\theta} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\theta}}, b_{\sigma^2_{\theta}}\right);$

* Default setting: $a_{\sigma^2_{\theta}} = 3$, $b_{\sigma^2_{\theta}} = 2.$

$\sigma^2_{\eta} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\eta}}, b_{\sigma^2_{\eta}}\right);$

* Default setting: $a_{\sigma^2_{\eta}} = 3$, $b_{\sigma^2_{\eta}} = 2.$

$\rho \sim \text{Uniform}\left(a_{\phi}, b_{\phi}\right);$

* Default setting: $a_{\phi} = 0,\ b_{\phi} = 1.$

$\phi \sim \text{Uniform}\left(a_{\phi}, b_{\phi}\right);$

* Default setting: $a_{\phi} = \log(0.9999)/(-(m-1))$, $b_{\phi} = \log(0.0001)/(-1).$

## Default Initial Values
* $\beta_j = 0$ for all $j$;

* $\theta_j = 0$ for all $j$;

* $\eta_j = 0$ for all $j$;

* $\sigma^2_{\theta} = 1.00$;

* $\sigma^2_{\eta} = 1.00$;

* $\rho = 0.50*\left(b_{\phi} - a_{\phi}\right)$;

* $\phi = 0.01\left(b_{\phi} - a_{\phi}\right)$.

## Alternate Likelihood: Gaussian
$Y_{ij}|\boldsymbol{\beta}, \boldsymbol{\theta}_i, \sigma^2_{\epsilon} \stackrel{\text{ind}}{\sim} \text{Normal}\left(\textbf{x}_{ij}^{\text{T}} \boldsymbol{\beta} + \sum_{k=1}^{m_{ij}} \text{z}_{ijk} \theta_i\left(k\right), \sigma^2_{\epsilon}\right),\ i=1,...,s;\ j=1,...,n_i;$

* $\sigma^2_{\epsilon} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\epsilon}}, b_{\sigma^2_{\epsilon}}\right);$ 

* Default setting: $a_{\sigma^2_{\epsilon}} = 0.01$, $b_{\sigma^2_{\epsilon}} = 0.01$; 

* Default initial value: $\sigma^2_{\epsilon} = 1.00$.

## Alternate Likelihood: Negative Binomial
$Y_{ij}|\boldsymbol{\beta}, \boldsymbol{\theta}, r \stackrel{\text{ind}}{\sim} \text{Negative Binomial}\left\{r, \lambda_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)\right\},\ i=1,...,s;\ j=1,...,n_i;$

$\text{ln}\left\{\frac{\lambda_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)}{1 - \lambda_{ij}\left(\boldsymbol{\beta}, \boldsymbol{\theta}_i\right)}\right\} = \text{O}_{ij} + \textbf{x}_{ij}^{\text{T}} \boldsymbol{\beta} + \sum_{k=1}^{m_{ij}} \text{z}_{ijk} \theta_i\left(k\right).$

* $r \sim \text{Discrete Uniform}\left[a_r, b_r\right];$ 

* Default setting: $a_r = 1$, $b_r = 100$; 

* Default initial value: $r = b_r$.

## Likelihood Indicator
* likelihood_indicator $= 0$: Binomial; 

* likelihood_indicator $= 1$: Gaussian;

* likelihood_indicator $= 2$: Negative binomial.

## Special Notes
* Do not center the exposures. Instead, we recommend that they are only scaled at each outcome time period (e.g., by interquartile range).

