# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SpGPCW <- function(mcmc_samples, y, x, z, site_id, neighbors, metrop_var_phi_theta_trans, metrop_var_rho_trans, metrop_var_phi_eta_trans, sigma2_beta_prior = NULL, alpha_sigma2_theta_prior = NULL, beta_sigma2_theta_prior = NULL, a_phi_theta_prior = NULL, b_phi_theta_prior = NULL, a_rho_prior = NULL, b_rho_prior = NULL, alpha_sigma2_eta_prior = NULL, beta_sigma2_eta_prior = NULL, a_phi_eta_prior = NULL, b_phi_eta_prior = NULL, beta_init = NULL, theta_init = NULL, sigma2_theta_init = NULL, phi_theta_init = NULL, eta_init = NULL, rho_init = NULL, sigma2_eta_init = NULL, phi_eta_init = NULL, rho_zero_indicator = NULL) {
    .Call(`_SpGPCW_SpGPCW`, mcmc_samples, y, x, z, site_id, neighbors, metrop_var_phi_theta_trans, metrop_var_rho_trans, metrop_var_phi_eta_trans, sigma2_beta_prior, alpha_sigma2_theta_prior, beta_sigma2_theta_prior, a_phi_theta_prior, b_phi_theta_prior, a_rho_prior, b_rho_prior, alpha_sigma2_eta_prior, beta_sigma2_eta_prior, a_phi_eta_prior, b_phi_eta_prior, beta_init, theta_init, sigma2_theta_init, phi_theta_init, eta_init, rho_init, sigma2_eta_init, phi_eta_init, rho_zero_indicator)
}

beta_update <- function(x, z, site_id, sigma2_beta, w, gamma, theta_old, eta_old) {
    .Call(`_SpGPCW_beta_update`, x, z, site_id, sigma2_beta, w, gamma, theta_old, eta_old)
}

eta_update <- function(eta_old, x, z, site_id, neighbors, w, gamma, beta, theta, rho_old, sigma2_eta_old, corr_inv_eta) {
    .Call(`_SpGPCW_eta_update`, eta_old, x, z, site_id, neighbors, w, gamma, beta, theta, rho_old, sigma2_eta_old, corr_inv_eta)
}

neg_two_loglike_update <- function(y, x, z, site_id, beta, theta, eta) {
    .Call(`_SpGPCW_neg_two_loglike_update`, y, x, z, site_id, beta, theta, eta)
}

phi_eta_update <- function(phi_eta_old, neighbors, eta, rho, sigma2_eta, temporal_corr_info_eta, a_phi_eta, b_phi_eta, metrop_var_phi_eta_trans, acctot_phi_eta_trans) {
    .Call(`_SpGPCW_phi_eta_update`, phi_eta_old, neighbors, eta, rho, sigma2_eta, temporal_corr_info_eta, a_phi_eta, b_phi_eta, metrop_var_phi_eta_trans, acctot_phi_eta_trans)
}

phi_theta_update <- function(phi_theta_old, theta, sigma2_theta, temporal_corr_info_theta, a_phi_theta, b_phi_theta, metrop_var_phi_theta_trans, acctot_phi_theta_trans) {
    .Call(`_SpGPCW_phi_theta_update`, phi_theta_old, theta, sigma2_theta, temporal_corr_info_theta, a_phi_theta, b_phi_theta, metrop_var_phi_theta_trans, acctot_phi_theta_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_SpGPCW_rcpp_pgdraw`, b, c)
}

rho_update <- function(rho_old, neighbors, eta, sigma2_eta_old, corr_inv_eta, a_rho, b_rho, metrop_var_rho_trans, acctot_rho_trans) {
    .Call(`_SpGPCW_rho_update`, rho_old, neighbors, eta, sigma2_eta_old, corr_inv_eta, a_rho, b_rho, metrop_var_rho_trans, acctot_rho_trans)
}

sigma2_eta_update <- function(neighbors, eta, rho, corr_inv_eta, alpha_sigma2_eta, beta_sigma2_eta) {
    .Call(`_SpGPCW_sigma2_eta_update`, neighbors, eta, rho, corr_inv_eta, alpha_sigma2_eta, beta_sigma2_eta)
}

sigma2_theta_update <- function(theta, corr_inv_theta, alpha_sigma2_theta, beta_sigma2_theta) {
    .Call(`_SpGPCW_sigma2_theta_update`, theta, corr_inv_theta, alpha_sigma2_theta, beta_sigma2_theta)
}

temporal_corr_fun <- function(m, phi) {
    .Call(`_SpGPCW_temporal_corr_fun`, m, phi)
}

theta_update <- function(x, z, site_id, w, gamma, beta, eta_old, sigma2_theta_old, corr_inv_theta) {
    .Call(`_SpGPCW_theta_update`, x, z, site_id, w, gamma, beta, eta_old, sigma2_theta_old, corr_inv_theta)
}

w_update <- function(y, x, z, site_id, beta_old, theta_old, eta_old) {
    .Call(`_SpGPCW_w_update`, y, x, z, site_id, beta_old, theta_old, eta_old)
}

