# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SpGPCW <- function(mcmc_samples, y, x, z, site_id, neighbors, metrop_var_rho_trans, metrop_var_phi_trans, sigma2_beta_prior = NULL, alpha_sigma2_theta_prior = NULL, beta_sigma2_theta_prior = NULL, a_rho_prior = NULL, b_rho_prior = NULL, alpha_sigma2_eta_prior = NULL, beta_sigma2_eta_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, beta_init = NULL, theta_init = NULL, sigma2_theta_init = NULL, eta_init = NULL, rho_init = NULL, sigma2_eta_init = NULL, phi_init = NULL, rho_zero_indicator = NULL) {
    .Call(`_SpGPCW_SpGPCW`, mcmc_samples, y, x, z, site_id, neighbors, metrop_var_rho_trans, metrop_var_phi_trans, sigma2_beta_prior, alpha_sigma2_theta_prior, beta_sigma2_theta_prior, a_rho_prior, b_rho_prior, alpha_sigma2_eta_prior, beta_sigma2_eta_prior, a_phi_prior, b_phi_prior, beta_init, theta_init, sigma2_theta_init, eta_init, rho_init, sigma2_eta_init, phi_init, rho_zero_indicator)
}

beta_update <- function(x, z, site_id, sigma2_beta, w, gamma, theta_old, eta_old) {
    .Call(`_SpGPCW_beta_update`, x, z, site_id, sigma2_beta, w, gamma, theta_old, eta_old)
}

eta_update <- function(eta_old, x, z, site_id, neighbors, w, gamma, beta, theta, rho_old, sigma2_eta_old, corr_inv) {
    .Call(`_SpGPCW_eta_update`, eta_old, x, z, site_id, neighbors, w, gamma, beta, theta, rho_old, sigma2_eta_old, corr_inv)
}

neg_two_loglike_update <- function(y, x, z, site_id, beta, theta, eta) {
    .Call(`_SpGPCW_neg_two_loglike_update`, y, x, z, site_id, beta, theta, eta)
}

phi_update <- function(phi_old, neighbors, theta, sigma2_theta, eta, rho, sigma2_eta, temporal_corr_info, a_phi, b_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_SpGPCW_phi_update`, phi_old, neighbors, theta, sigma2_theta, eta, rho, sigma2_eta, temporal_corr_info, a_phi, b_phi, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_SpGPCW_rcpp_pgdraw`, b, c)
}

rcpparma_hello_world <- function() {
    .Call(`_SpGPCW_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SpGPCW_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SpGPCW_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SpGPCW_rcpparma_bothproducts`, x)
}

rho_update <- function(rho_old, neighbors, eta, sigma2_eta_old, corr_inv, a_rho, b_rho, metrop_var_rho_trans, acctot_rho_trans) {
    .Call(`_SpGPCW_rho_update`, rho_old, neighbors, eta, sigma2_eta_old, corr_inv, a_rho, b_rho, metrop_var_rho_trans, acctot_rho_trans)
}

sigma2_eta_update <- function(neighbors, eta, rho, corr_inv, alpha_sigma2_eta, beta_sigma2_eta) {
    .Call(`_SpGPCW_sigma2_eta_update`, neighbors, eta, rho, corr_inv, alpha_sigma2_eta, beta_sigma2_eta)
}

sigma2_theta_update <- function(theta, corr_inv, alpha_sigma2_theta, beta_sigma2_theta) {
    .Call(`_SpGPCW_sigma2_theta_update`, theta, corr_inv, alpha_sigma2_theta, beta_sigma2_theta)
}

temporal_corr_fun <- function(m, phi) {
    .Call(`_SpGPCW_temporal_corr_fun`, m, phi)
}

theta_update <- function(x, z, site_id, w, gamma, beta, eta_old, sigma2_theta_old, corr_inv) {
    .Call(`_SpGPCW_theta_update`, x, z, site_id, w, gamma, beta, eta_old, sigma2_theta_old, corr_inv)
}

w_update <- function(y, x, z, site_id, beta_old, theta_old, eta_old) {
    .Call(`_SpGPCW_w_update`, y, x, z, site_id, beta_old, theta_old, eta_old)
}

